version: 0.2

env:
  variables:
    ECR_REPO: 852976468951.dkr.ecr.us-east-1.amazonaws.com
    ECR_REGION: us-east-1
    CONTAINER_NAME: lks-catalog-app
    CONTAINERTD: lks-catalog-container
    ACCESS_KEY: $Access_Key
    SECRET_KEY: $Secret_Key

phases:
  pre_build:
    commands:
      - echo "login to ecr"
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_REPO
  build:
    commands:
      - echo "run test and build docker"
      - |
        echo "AWS_ACCESS_KEY=$ACCESS_KEY
        AWS_SECRET_KEY=$SECRET_KEY" >> .env.production
      - docker build -t $CONTAINER_NAME .
      - docker tag $CONTAINER_NAME:latest $ECR_REPO/$CONTAINER_NAME:latest

  post_build:
    commands:
      - echo "push the image to ECR."
      - docker push $ECR_REPO/$CONTAINER_NAME:latest
      - printf '[{"name":"%s", "imageUri":"%s"}]' $CONTAINERTD $ECR_REPO/$CONTAINER_NAME:latest > imagedefinitions.json
      - echo "buildcomplete..."

reports:
  test-report:
    files:
      - "report/test-result.xml"
    file-format: JUNITXML

artifacts:
  files:
    - imagedefinitions.json
